version: '2'
services:
  web:
    image: botium/botium-box-ce:2.6.0
    ports:
     - "4000:4000"
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/box/ce13
      BOTIUMBOX_QUEUE_REDISURL: redis://redis:6379
      BOTIUMBOX_AGENT_NAME: Botium Agent 1
      DEBUG: botium*
    depends_on:
      - redis
      - prisma
    restart: always
    volumes:
      - ./testsets:/app/server/testsets
      - ./testsets:/app/agent/testsets
      - ./botiumwork:/app/server/botiumwork
      - ./botiumwork:/app/agent/botiumwork
      - ./resources:/app/server/resources
      - ./resources:/app/agent/resources
  prisma:
    image: prismagraphql/prisma:1.34.10
    depends_on:
      - mysql
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: always
    ports:
    - "6379:6379"
