apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: botium-box-storage
  namespace: botium-box-ce
  labels:
    name: botium-box-storage
    app: botium-box-ce
    tier: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: box
  namespace: botium-box-ce
  labels:
    name: box
    app: botium-box-ce
    tier: frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: box
        app: botium-box-ce
        tier: frontend
    spec:
      containers:
        - name: box
          image: botium/botium-box-ce:2.6.1
          ports:
            - name: box-4000
              containerPort: 4000
          volumeMounts:
          - mountPath: "/app/storage"
            name: storage
          env:
            - name: BOTIUMBOX_AGENT_NAME
              value: Botium Agent 1
            - name: DEBUG
              value: botium*
            - name: TESTSETDIR
              value: /app/storage/testsets
            - name: RESOURCESDIR
              value: /app/storage/resources
            - name: TEMPDIR
              value: /app/storage/botiumwork
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  name: botium-box-ce-configmap
                  key: LICENSE_KEY
            - name: PRISMA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: botium-box-ce-configmap
                  key: PRISMA_ENDPOINT
            - name: BOTIUMBOX_QUEUE_REDISURL
              valueFrom:
                configMapKeyRef:
                  name: botium-box-ce-configmap
                  key: BOTIUMBOX_QUEUE_REDISURL
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: botium-box-storage
---
apiVersion: v1
kind: Service
metadata:
  name: box
  namespace: botium-box-ce
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    name: box
    app: botium-box-ce
